=== ved256/coba/trunk/custom/configurations/streetreffiles/VSH.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT field (vendorSource?, where?)*>
<!ATTLIST field
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	lookup CDATA #IMPLIED
	valueOf CDATA #IMPLIED
	dataType (STRING | DATE | DATETIME | NUMBER | DECIMAL | TIME) "STRING"
	table CDATA #IMPLIED
>
<!ELEMENT occurrence (occurrenceFields?, option*, vendorSource?, where?)*>
<!ATTLIST occurrence
	table ID #REQUIRED
	update_equal_rank CDATA #IMPLIED
	update_empty_field CDATA #IMPLIED
	update_high_ranked_source CDATA #IMPLIED
	process_unknown_vendor CDATA #IMPLIED
>
<!ELEMENT occurrenceFields (field*)>
<!ATTLIST occurrenceFields
	process_unknown_vendor CDATA #IMPLIED
>

<!ELEMENT option ((occurrenceFields?, where?)*, vendorSource, (occurrenceFields?, where?)*)>
<!ATTLIST option
	id ID #REQUIRED
	update_equal_rank CDATA #IMPLIED
	update_empty_field CDATA #IMPLIED
	update_high_ranked_source CDATA #IMPLIED
	process_unknown_vendor CDATA #IMPLIED
>
<!ELEMENT source EMPTY>
<!ATTLIST source
	vendor CDATA #REQUIRED
	rank CDATA #IMPLIED
	weight CDATA #IMPLIED
>
<!ELEMENT vendorSource (source*)>
<!ATTLIST vendorSource
	expiration_timespan CDATA #IMPLIED
>
<!ELEMENT vsh (occurrence+)>
<!ATTLIST vsh
	update_equal_rank (true | false) "true"
	update_empty_field (none | low_equal | equal) "none"
	process_unknown_vendor (low | high | none ) "low"
	update_high_ranked_source (yes | no) "no"
>
<!ELEMENT where (field*)>
<!ATTLIST where
	match CDATA #IMPLIED
>

=== ved256/coba/trunk/custom/configurations/streetreffiles/VSH.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vsh SYSTEM "VSH.dtd">
<vsh process_unknown_vendor="low" update_empty_field="low_equal" update_equal_rank="true">
  <occurrence table="ft_t_issu">
    <vendorSource>
      <source vendor="BB" rank="1" />
      <source vendor="BBEXT" rank="2" />
      <source vendor="MORNSTAR" rank="3" />
    </vendorSource>
                <occurrenceFields>
                  <field name="ft_t_issu.denom_curr_cde" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_issu.mat_exp_tms" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_issu.iss_tms" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_issu.nom_val_unit_camt" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_issu.distribution_curr_cde" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
            </occurrenceFields>
  </occurrence>
  <occurrence table="ft_t_bdch">
    <vendorSource>
      <source vendor="BB" rank="1" />
      <source vendor="BBEXT" rank="2" />
      <source vendor="MORNSTAR" rank="3" />
    </vendorSource>
                <occurrenceFields>
                  <field name="ft_t_bdch.dted_tms" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_bdch.cpn_typ" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_bdch.acrd_in_prcng_bas_typ" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_bdch.call_stat_typ" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_bdch.call_typ" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_bdch.put_typ" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_bdch.put_stat_typ" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_bdch.covered_ind" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_bdch.qt_pct_par_ind" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
            </occurrenceFields>
  </occurrence>
  <occurrence table="ft_t_bdst">
    <vendorSource>
      <source vendor="BB" rank="1" />
      <source vendor="BBEXT" rank="2" />
      <source vendor="MORNSTAR" rank="3" />
    </vendorSource>
                <occurrenceFields>
                  <field name="ft_t_bdst.crrnt_iss_camt" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_bdst.outst_camt" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_bdst.nxt_call_dte" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
                  <field name="ft_t_bdst.ex_div_dy_qty" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
            </occurrenceFields>
  </occurrence>
  <occurrence table="ft_t_iedf">
    <vendorSource>
      <source vendor="BB" rank="1" />
      <source vendor="BBEXT" rank="2" />
      <source vendor="MORNSTAR" rank="3" />
    </vendorSource>
                <occurrenceFields>
                  <field name="ft_t_iedf.rtfx_cal_id" dataType="STRING">
                        <vendorSource>
                              <source vendor="RMB" rank="1"/>
                              <source vendor="BB" rank="2"/>
                              <source vendor="BBEXT" rank="3"/>
                              <source vendor="MORNSTAR" rank="4"/>
                        </vendorSource>
                  </field>
            </occurrenceFields>
  </occurrence>
  <occurrence table="ft_t_isas">
    <vendorSource>
      <source vendor="BB" rank="1" />
      <source vendor="BBEXT" rank="2" />
      <source vendor="MORNSTAR" rank="3" />
    </vendorSource>
                <occurrenceFields>
